federation_version: 2
subgraphs:
  locations:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  reviews:
    routing_url: http://localhost:4000
    schema:
      subgraph_url: http://localhost:4000